### ISSUE TITLE
VS2022 Community try to set readonly property Text

### ISSUE THREAD

**Issue by miaolinopenvox** [Code-Artist/CodeArtEng.Diagnostics#2] opened 2022-05-23 05:26 UTC
Code generated by VS2022 community always generate code like this:

this.diagnosticsRichTextBox1.Text = "";

but Text property is readonly ,so have to delete this like manually before build.

VS200 version 17.1.0
CodeArtEng.Diagnostics v4.0.2 from nuget

**Comment by Code-Artist** [comment] 2022-05-25 12:35
My setup as follow:
- VS2022 Version 17.0.6.
- .NET Framework 4.5

I am not able to produce the issue that you mentioned.
Need further investigation.

**Comment by Code-Artist** [comment] 2022-05-25 12:43
@miaolinopenvox   Question: Is this only happened on VS2022 Version 17.1.0?

**Comment by Code-Artist** [comment] 2022-07-31 00:42
Closing issue due to not enough information and not reproducible.

**Closed as completed by Code-Artist** 2022-07-31 00:42 UTC
Labels: question
